const SETRECIEVER = 'SETRECIEVER';
const SETSENDAMOUNT = 'SETSENDAMOUNT';
const SETLOADING = 'SETLOADING';
const SETISSCAN = 'SETISSCAN';

export {
    SETRECIEVER,
    SETSENDAMOUNT,
    SETLOADING,
    SETISSCAN
}