const SIGNUP = 'SIGNUP';
const LOGIN = 'LOGIN';

const SETRECIEVER = 'SETRECIEVER';
const SETSENDAMOUNT = 'SETSENDAMOUNT';
const SETLOADING = 'SETLOADING';
const SETISSCAN = 'SETISSCAN';
const SETOFFLINEDATA = 'SETOFFLINEDATA';
const SETERR = 'SETERR';

const SETTOKEN = 'SETTOKEN';
const SETUSERDATA = 'SETUSERDATA';
const SETAUTHERR = 'SETAUTHERR';

export {
    SIGNUP,
    LOGIN,

    SETRECIEVER,
    SETSENDAMOUNT,
    SETLOADING,
    SETISSCAN,
    SETOFFLINEDATA,
    SETERR,
    
    SETTOKEN,
    SETUSERDATA,
    SETAUTHERR
}