const SIGNUP = 'SIGNUP';
const LOGIN = 'LOGIN';

const SETRECIEVER = 'SETRECIEVER';
const SETSENDAMOUNT = 'SETSENDAMOUNT';
const SETLOADING = 'SETLOADING';
const SETISSCAN = 'SETISSCAN';


export {
    SIGNUP,
    LOGIN,

    SETRECIEVER,
    SETSENDAMOUNT,
    SETLOADING,
    SETISSCAN
}